# Generated by Django 3.2.18 on 2023-05-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_auto_20230502_0950"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_connection",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="derniere connexion"),
        ),
    ]
